
name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: NICK3ON
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push Snake
        uses: EndBug/add-and-commit@v7
        with:
          message: "Generate Snake"
          add: "dist/github-contribution-grid-snake.svg"
